### PR TITLE
fix ctypes and filename separator

### PR DESCRIPTION
**Pull request by gordonaspin**
to make app work on Linux

### CODE REVIEW

**Comment by gBloxy** [comment]
thank you,
but how can we set the DPI awarness to aware on Linux systems ?
You removed this line windll.shcore.SetProcessDpiAwareness(2) but it's very util because it assure that the window is entirely visible on the screen. On littles screens when windows rescale all the applications, the game window can be bigger than the screen in during the extreme level.

**Comment by gBloxy** [comment]
what about this line ? os.environ['SDL_VIDEO_X11_NET_WM_DPI_SCALE'] = '1' I found it on internet but I don't have Linux to test it

**Comment by gordonaspin** [comment]
I'll try it out. What is supposed to be the effect ? What problem is resolved with the windows version ?

**Comment by gordonaspin** [comment]
SDL_VIDEO_X11_NET_WM_DPI_SCALE is not an available hint in SDL2 (at least I cannot find it in the C language header files in /usr/include/SDL2/SDL_hints.h). Where did you find this information ? I have googled and cannot find a reference to SDL_VIDEO_X11_NET_WM_DPI_SCALE anywhere.

**Comment by gBloxy** [comment]
I didn't find anything on changing the DPI awareness on Linux with python on google, so ChatGPT tried to help me.
if there isn't any other solutions to replace this line for linux, maybe we can not do it.
Is the version working on macOS too ?

**Pull request merged**
